name: Lint, Test, Build
on: [push, pull_request]
jobs:
    lint-test-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v1
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Install dependencies
              run: yarn
            - name: Run Tests
              run: yarn test
            - name: Build App
              run: yarn build
